name: build
on: [push]
jobs:
        runs-on: ubuntu-latest
        steps:
                - uses: actions/checkout@v2
                - uses: actions-rs/cargo@v1
                  with:
                          command: build
                          arguments: --all-features --verbose

